shell /usr/bin/fish

background_opacity 0.85
dynamic_background_opacity no

background #202020
foreground #B4B4B0
selection_background #595237
selection_foreground #DFC86D
cursor #DFC86D
cursor_text_color #202020

color0 #202020
color1 #C50F1F
color2 #13A10E
color3 #A49355
color4 #595237
color5 #877A4B
color6 #A49355
color7 #B4B4B0
color8 #212121
color9 #E74856
color10 #16C60C
color11 #DFC86D
color12 #A49355
color13 #877A4B
color14 #DFC86D
color15 #F2F2F2

font_family JetBrainsMono Nerd Font
font_size 13.0
confirm_os_window_close 0

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+kp_plus change_font_size all +2.0
map ctrl+kp_minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# faster scrolling for touchpad
wheel_scroll_multiplier 15.0
