# ################################################################
# Window Rules
# ################################################################

# Make all windows have blue borders and no rounding (already set globally)
